"use client";

import Link from "next/link";
import {
  ArrowLeft,
  Database,
  Users,
  Calendar,
  Shield,
  Code,
  FileText,
  ExternalLink,
  Table,
  GitBranch,
  BookOpen,
} from "lucide-react";

export default function DatasheetPage() {
  return (
    <div className="bg-gradient-to-br from-slate-50 via-white to-emerald-50">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-emerald-100/50 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-violet-100/50 rounded-full blur-3xl" />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-4 py-8 sm:py-12">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-slate-600 hover:text-slate-800 transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm font-medium">Back to Home</span>
        </Link>

        {/* Header */}
        <div className="text-center mb-10">
          <div className="w-16 h-16 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg shadow-emerald-200">
            <Database className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-800 mb-3">
            Datasheet for SmartPlayFPL Dataset
          </h1>
          <p className="text-slate-600 max-w-lg mx-auto text-sm sm:text-base">
            Following the framework proposed by{" "}
            <a
              href="https://arxiv.org/abs/1803.09010"
              target="_blank"
              rel="noopener noreferrer"
              className="text-emerald-600 hover:underline"
            >
              Gebru et al. (2021)
            </a>{" "}
            - &quot;Datasheets for Datasets&quot;
          </p>
        </div>

        {/* Motivation Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-emerald-50">
            <BookOpen className="w-5 h-5 text-emerald-600" />
            <h2 className="font-bold text-slate-800">Motivation</h2>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">For what purpose was the dataset created?</h3>
              <p className="text-slate-600 text-sm mb-3">
                SmartPlayFPL was created to provide a semantic knowledge graph representation of Fantasy Premier League (FPL) data. The purpose is to enable intelligent decision-making for FPL managers through:
              </p>
              <ul className="list-disc list-inside text-slate-600 text-sm space-y-1 ml-2">
                <li>OWL-based reasoning for automatic player classification</li>
                <li>SPARQL queries for complex player discovery</li>
                <li>SHACL validation for squad constraint checking</li>
                <li>Provenance tracking for explainable recommendations</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Who created the dataset?</h3>
              <ul className="text-slate-600 text-sm space-y-1 mb-3">
                <li><strong>Data Source:</strong> Fantasy Premier League (owned by the Premier League)</li>
                <li><strong>Data Curator/Researcher:</strong> Qazybek Beken, UC Berkeley · School of Information</li>
                <li><strong>Institution:</strong> UC Berkeley, School of Information</li>
                <li><strong>Purpose:</strong> Research demonstration of Semantic Web technologies (RDF, OWL, SHACL, SPARQL) applied to a real-world domain</li>
              </ul>
              <p className="text-slate-600 text-sm italic bg-slate-50 p-3 rounded-lg border border-slate-200">
                Note: The underlying statistical data is generated by Fantasy Premier League managers and the Premier League. This dataset represents the curation, semantic enrichment, and knowledge graph transformation of that publicly available data.
              </p>
            </div>
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Who funded the creation of the dataset?</h3>
              <p className="text-slate-600 text-sm">
                This dataset was created as a personal/academic project with no external funding.
              </p>
            </div>
          </div>
        </section>

        {/* Composition Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-blue-50">
            <Table className="w-5 h-5 text-blue-600" />
            <h2 className="font-bold text-slate-800">Composition</h2>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="font-semibold text-slate-800 mb-3">What do the instances represent?</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-slate-200">
                      <th className="text-left py-2 px-3 font-semibold text-slate-700">Entity Type</th>
                      <th className="text-left py-2 px-3 font-semibold text-slate-700">Count</th>
                      <th className="text-left py-2 px-3 font-semibold text-slate-700">Description</th>
                    </tr>
                  </thead>
                  <tbody className="text-slate-600">
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3 font-medium">Players</td>
                      <td className="py-2 px-3">755</td>
                      <td className="py-2 px-3">Premier League footballers with stats</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3 font-medium">Teams</td>
                      <td className="py-2 px-3">20</td>
                      <td className="py-2 px-3">Premier League clubs</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3 font-medium">Positions</td>
                      <td className="py-2 px-3">4</td>
                      <td className="py-2 px-3">GKP, DEF, MID, FWD</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3 font-medium">Smart Tags</td>
                      <td className="py-2 px-3">12</td>
                      <td className="py-2 px-3">OWL-inferred player classifications</td>
                    </tr>
                    <tr>
                      <td className="py-2 px-3 font-medium">Fixtures</td>
                      <td className="py-2 px-3">~380</td>
                      <td className="py-2 px-3">Scheduled matches with difficulty ratings</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Dataset Size</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Total RDF Triples:</strong> ~23,003</li>
                <li><strong>Players:</strong> 755 (complete population for 2024/25 season)</li>
                <li><strong>Inferred Classifications:</strong> Variable (depends on current season data)</li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-3">Player Entity Properties</h3>
              <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs sm:text-sm text-slate-300 overflow-x-auto">
                <pre>{`- id (integer): Unique FPL identifier
- web_name (string): Display name
- team (integer → Team): Club reference
- position (string): GKP/DEF/MID/FWD
- price (decimal): Current price in £millions
- form (decimal): Recent performance score (0-10)
- total_points (integer): Season points accumulated
- ownership (decimal): Percentage of managers owning
- status (string): a/d/i/s/u (availability)
- minutes (integer): Total minutes played
- goals, assists (integer): Goal contributions
- xG, xA (decimal): Expected goals/assists`}</pre>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-3">Inferred Smart Tags (OWL Classes)</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm">
                {[
                  { tag: "CaptainCandidate", rule: "form >= 7.0 AND status = 'a'" },
                  { tag: "TransferTarget", rule: "form >= 5.0 AND points_per_price >= 12" },
                  { tag: "DifferentialPick", rule: "ownership < 10% AND form >= 5.0" },
                  { tag: "RotationRisk", rule: "minutes < 800 AND price > 6.0" },
                  { tag: "ValuePick", rule: "points_per_price >= 15" },
                  { tag: "PremiumAsset", rule: "price >= 10.0 AND form >= 6.0" },
                  { tag: "InjuryConcern", rule: "status != 'a' OR chance < 75" },
                  { tag: "MustBuy", rule: "form >= 6.0 AND ppp >= 12 AND status = 'a'" },
                ].map((item) => (
                  <div key={item.tag} className="bg-slate-50 rounded-lg p-3 border border-slate-200">
                    <span className="font-semibold text-emerald-700">{item.tag}</span>
                    <p className="text-slate-500 text-xs mt-1">{item.rule}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Collection Process Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-violet-50">
            <GitBranch className="w-5 h-5 text-violet-600" />
            <h2 className="font-bold text-slate-800">Collection Process</h2>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">How was the data acquired?</h3>
              <p className="text-slate-600 text-sm mb-3">
                Data is acquired via the official FPL API:
              </p>
              <div className="bg-slate-900 rounded-lg p-3 font-mono text-xs sm:text-sm text-emerald-400 overflow-x-auto">
                https://fantasy.premierleague.com/api/bootstrap-static/
              </div>
              <p className="text-slate-500 text-xs mt-2">
                This is the same API used by the official FPL website and mobile apps.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Collection Mechanisms</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Python httpx:</strong> Asynchronous HTTP client</li>
                <li><strong>Caching:</strong> In-memory cache with 5-minute TTL</li>
                <li><strong>Transformation:</strong> Raw JSON → Pydantic models → RDF triples</li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Timeframe</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Snapshot frequency:</strong> Real-time (on API request)</li>
                <li><strong>Season scope:</strong> 2024/25 Premier League season</li>
                <li><strong>Historical data:</strong> Current season only</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Uses Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-amber-50">
            <Users className="w-5 h-5 text-amber-600" />
            <h2 className="font-bold text-slate-800">Uses</h2>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">What tasks has the dataset been used for?</h3>
              <ul className="list-disc list-inside text-slate-600 text-sm space-y-1 ml-2">
                <li><strong>Squad Building:</strong> Generating optimal 15-player FPL squads</li>
                <li><strong>Player Discovery:</strong> Faceted search with OWL-inferred classifications</li>
                <li><strong>Constraint Validation:</strong> SHACL-based squad rule checking</li>
                <li><strong>Player Comparison:</strong> Finding similar players via SPARQL</li>
                <li><strong>Explainability:</strong> Provenance tracking for recommendations</li>
              </ul>
            </div>

            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <h3 className="font-semibold text-red-800 mb-2">Tasks the dataset should NOT be used for</h3>
              <ul className="list-disc list-inside text-red-700 text-sm space-y-1 ml-2">
                <li><strong>Gambling/Betting:</strong> This dataset is for entertainment purposes only</li>
                <li><strong>Player valuation:</strong> FPL prices don&apos;t reflect real transfer values</li>
                <li><strong>Injury prediction:</strong> News field is informational, not medical</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Distribution Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-cyan-50">
            <Shield className="w-5 h-5 text-cyan-600" />
            <h2 className="font-bold text-slate-800">Distribution & Licensing</h2>
          </div>
          <div className="p-6 space-y-4">
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">How is the dataset distributed?</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Format:</strong> In-memory RDF graph (not distributed as static file)</li>
                <li><strong>Access:</strong> Via REST API endpoints</li>
                <li><strong>Serialisation available:</strong> Turtle, JSON-LD, N-Triples</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Licensing</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Code:</strong> MIT Licence</li>
                <li><strong>Data:</strong> Subject to FPL API Terms of Service</li>
                <li><strong>Ontology:</strong> CC BY 4.0</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Technical Specifications Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-indigo-50">
            <Code className="w-5 h-5 text-indigo-600" />
            <h2 className="font-bold text-slate-800">Technical Specifications</h2>
          </div>
          <div className="p-6 space-y-6">
            <div>
              <h3 className="font-semibold text-slate-800 mb-3">Technology Stack</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-slate-200">
                      <th className="text-left py-2 px-3 font-semibold text-slate-700">Component</th>
                      <th className="text-left py-2 px-3 font-semibold text-slate-700">Technology</th>
                    </tr>
                  </thead>
                  <tbody className="text-slate-600">
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">RDF Storage</td>
                      <td className="py-2 px-3">RDFLib (in-memory)</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">OWL Reasoning</td>
                      <td className="py-2 px-3">OWLRL</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">SHACL Validation</td>
                      <td className="py-2 px-3">PySHACL</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">Query Language</td>
                      <td className="py-2 px-3">SPARQL 1.1</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">External Linking</td>
                      <td className="py-2 px-3">Wikidata SPARQL</td>
                    </tr>
                    <tr className="border-b border-slate-100">
                      <td className="py-2 px-3">API Framework</td>
                      <td className="py-2 px-3">FastAPI</td>
                    </tr>
                    <tr>
                      <td className="py-2 px-3">Frontend</td>
                      <td className="py-2 px-3">Next.js + React</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-3">Ontology Namespace</h3>
              <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs sm:text-sm text-slate-300 overflow-x-auto">
                <pre>{`@prefix fpl: <http://fantasykg.org/ontology#> .

# Core Classes
fpl:Player, fpl:Team, fpl:Fixture, fpl:Position

# Object Properties
fpl:playsFor, fpl:hasPosition, fpl:hasFixture, fpl:hasOpponent

# Data Properties
fpl:price, fpl:form, fpl:totalPoints, fpl:ownership, fpl:status`}</pre>
              </div>
            </div>

            <div>
              <h3 className="font-semibold text-slate-800 mb-2">SHACL Squad Validation Constraints</h3>
              <ul className="list-disc list-inside text-slate-600 text-sm space-y-1 ml-2">
                <li>Exactly 15 players</li>
                <li>Budget ≤ £100.0m</li>
                <li>2 GKP, 5 DEF, 5 MID, 3 FWD</li>
                <li>Maximum 3 players per team</li>
                <li>Valid formation (e.g., 3-4-3, 4-4-2)</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Maintenance Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-green-50">
            <Calendar className="w-5 h-5 text-green-600" />
            <h2 className="font-bold text-slate-800">Maintenance</h2>
          </div>
          <div className="p-6 space-y-4">
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Maintainer</h3>
              <p className="text-slate-600 text-sm">Qazybek Beken</p>
            </div>
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Update Frequency</h3>
              <ul className="text-slate-600 text-sm space-y-1">
                <li><strong>Real-time:</strong> Every API request (with 5-minute cache)</li>
                <li><strong>Season reset:</strong> New season data available August each year</li>
                <li><strong>Gameweek updates:</strong> After each Premier League matchday</li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-slate-800 mb-2">Contact</h3>
              <a
                href="https://github.com/qazybekb/smartplayfpl/issues"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 text-emerald-600 hover:text-emerald-700 text-sm"
              >
                GitHub Issues <ExternalLink className="w-4 h-4" />
              </a>
            </div>
          </div>
        </section>

        {/* Citation Section */}
        <section className="bg-white rounded-2xl border border-slate-200 shadow-lg overflow-hidden mb-6">
          <div className="px-6 py-4 border-b border-slate-100 flex items-center gap-3 bg-rose-50">
            <FileText className="w-5 h-5 text-rose-600" />
            <h2 className="font-bold text-slate-800">Citation</h2>
          </div>
          <div className="p-6">
            <p className="text-slate-600 text-sm mb-3">
              If you use this dataset or the SmartPlayFPL system, please cite:
            </p>
            <div className="bg-slate-900 rounded-lg p-4 font-mono text-xs sm:text-sm text-slate-300 overflow-x-auto">
              <pre>{`@software{smartplayfpl2024,
  author = {Beken, Qazybek},
  title = {SmartPlayFPL: A Knowledge Graph for Fantasy Premier League},
  year = {2024},
  url = {https://github.com/qazybekb/smartplayfpl},
  note = {RDF/OWL/SHACL-based FPL decision support system}
}`}</pre>
            </div>
          </div>
        </section>

        {/* Footer Reference */}
        <p className="text-center text-slate-400 text-xs">
          This datasheet follows the template proposed in: Gebru, T., et al. (2021). Datasheets for Datasets. Communications of the ACM, 64(12), 86-92.
        </p>
      </div>
    </div>
  );
}
